//The URLS are setup here
export const urlConstants = {
  AUTH: {
    REGISTRATION: "auth/create-account",
    LOGIN: "auth/login",
    LOGIN_TWO_FA: "auth/login/2fa",
    SEND_PASSWORD_RESET_LINK: "auth/password/reset",
    RESET_PASSWORD: "auth/password/change",
    RESEND_VERIFICATION: "auth/verify/resend",
    VERIFY_RESET_PASSWORD_TOKEN: "auth/validate/password/:token",
    VERIFY_ACCOUNT: "auth/account/verify/",
    VALIDATE_REFERRAL: "auth/referral/validate/",
  },
  ACCOUNT: {
    UPDATE_ACCOUNT: "account/update",
    CHANGE_PASSWORD: "account/password/change",
    FIND_ACCOUNT_BY_ID: "account/user/:id",
    FIND_ACCOUNT: "account/user",
    INITIATE_TWO_FA: "account/initiate/2fa",
    ACTIVATE_TWO_FA: "account/activate/2fa",
    DEACTIVATE_TWO_FA: "account/deactivate/2fa",
    SEND_EMAIL_TWO_FA: "account/2fa/email",
    GET_LOGGED_IN_USER_PROFILE: "account/",
  },
  BOOKMARK: {
    FETCH_BOOKMARKS: "bookmark/",
    FETCH_A_BOOKMARK: "bookmark/:id",
    CREATE_BOOKMARK: "bookmark/",
    DELETE_A_BOOKMARK: "bookmark/:id",
  },
  CHAT: {
    GET_USER_MESSAGES: "chat/",
  },
  COLLECTION: {
    GET_COLLECTION_TYPES: "/collection-type/",
    GET_A_COLLECTION_TYPE: "/collection-type/:id",
    GET_COLLECTIONS: "/collection/",
    GET_A_COLLECTION: "/collection/:id",
    CREATE_A_COLLECTION: "/collection/",
    CREATE_MULTIPLE_COLLECTIONS: "/collection/many",
    UPDATE_MANY_COLLECTIONS: "/collection/many/update",
    UPDATE_A_COLLECTION: "/collection/:id",
    DELETE_A_COLLECTION: "/collection/:id",
  },
  CONNECTION_FILTER: {
    CREATE: "/conn-filter/",
    GET: "/conn-filter/user",
    UPDATE: "/conn-filter/",
  },
  FEED: {
    FETCH_ALL: "/feeds/",
    FETCH_BY_ID: "/feeds/:id",
    DISMISS_A_FEED: "/feeds/:id/dismiss",
    DISMISS_ALL: "/feeds/dismiss/all",
    CREATE: "/feeds/",
  },
  FILE: {
    UPLOAD: "/upload/",
    GET_ALL: "/upload/",
    GET_AN_UPLOAD: "/upload/:id",
  },
  INVITE: {
    ALL: "/invite/",
    AN_INVITE: "/invite/:id",
    SEND: "/invite/",
    ACCEPT: "/invite/:id/accept",
    DECLINE: "/invite/:id/decline",
    CANCEL: "/invite/:id/cancel",
  },
  PAYMENT: {
    CREATE_ORDER: "payment/",
    VALIDATE_PAYMENT: "payment/validate",
    RELEASE_PAYMENT: "payment/release",
    PAYMENT_METHODS: "payment/coins",
    ACTIVE_RPC: "payment/rpc",
  },
  REFERRALS: {
    USER: "referrals",
    STATS: "referrals/stats",
    INVITE: "referrals/invite",
  },
  REVIEWS: {
    ADD: "reviews/",
    ALL: "reviews/",
    A_REVIEW: "reviews/:id",
    UPDATE: "reviews/:id",
    DELETE: "reviews/:id",
  },
  SETTINGS: {
    SITE: "settings/",
  },
  TRANSACTION: {
    EXCHANGE: "transaction/exchange",
    STATS: "transaction/stats",
    AGGREGATE_STATS: "transaction/aggregate/stats",
    A_TRANSACTION: "transaction/:id",
    ALL: "transaction/",
  },
  USER_VERIFICATION: {
    CREATE_SESSION: "user-verification/session/new",
    SESSION_ATTEMPTS: "user-verification/session/attempts",
    GET_USER_VERIFICATION: "user-verification/user",
    SESSION_MEDIA: "user-verification/session/media",
    DELETE_SESSION: "user-verification/session/delete",
  },
  WALLET: {
    USER: "wallet/",
    SINGLE: "wallet/coin",
  },
  WITHDRAWAL: {
    CREATE: "withdrawals/",
    ALL: "withdrawals/",
  },
};
